### PR TITLE
Removed external Conda package manifest files.

### PR DESCRIPTION
**Pull request by ashalper-usgs**

### CODE REVIEW

**Comment by isuftin** [comment]
Is `nhmusgs-base/spec-file.txt` needed at all at this point? Does it get used?

**Comment by ashalper-usgs** [comment]
No, it never was referenced on canonical `master`. Only "on the drawing board".

**Comment by isuftin** [comment]
Might just want to remove it completely

**Comment by ashalper-usgs** [comment]
Sorry, I thought that's what I was doing. Fixed now.

**Comment by isuftin** [comment]
Looks good. Go for merge

**Pull request merged**
